language: node_js
os:
  - linux
  - windows

node_js:
  - '12'

# https://travis-ci.community/t/timeout-after-build-finished-and-succeeded/1336/2
env:
  - YARN_GPG=no

before_script:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then chmod +x ./cc-test-reporter ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then ./cc-test-reporter before-build ; fi

after_script:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then ./cc-test-reporter format-coverage -t lcov ./coverage/lcov.info ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT ; fi

install:
  - npm install

script:
  - npm run build
  - npm run test:report

deploy:
  provider: script
  script:
    - npx semantic-release
  skip_cleanup: true
  on:
    branch: master
    condition: $TRAVIS_OS_NAME = linux
